# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 55a0f9fe38b014c3350a8c4909c59d0c655c883dd649018e0cb4981c9b438f34c7a00f51350797be712992d8efbc4e8f39ed2aee90357190f4cb0d480de09517

test:
  secret_key_base: 6fafa155e0c3d9705587286b31a71af6fbf1ac905b025ac366cd9a9ab59926432b6d16d4a7226c65551597b48631e1aa3dd4dd20c7595f2f7a6b06a0e4974f2d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
